# Generated by Django 5.2.7 on 2026-09-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(blank=True, choices=[('membership_plan', 'Membership & Day Pass Trial'), ('personal_training', '1-on-1 Master Coaching & Assessment'), ('biometric_scan', 'InBody 570 Biometric Scan'), ('nutrition_consultation', 'Nutrition & Pro Shop Order'), ('group_classes', 'Corporate & Group Strength Program'), ('other', 'General Enquiry & Facility Access')], default='other', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
